<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="kafka.consumer.MetricsTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2015-03-27T21:40:17" hostname="airbears2-10-142-35-31.AirBears2.1918.Berkeley.EDU" time="4.745">
  <properties/>
  <testcase name="testMetricsReporterAfterDeletingTopic" classname="kafka.consumer.MetricsTest" time="1.661"/>
  <testcase name="testMetricsLeak" classname="kafka.consumer.MetricsTest" time="3.083"/>
  <system-out><![CDATA[[2015-03-27 14:40:20,160] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor:103)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at kafka.utils.Utils$.read(Utils.scala:380)
	at kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54)
	at kafka.network.Processor.read(SocketServer.scala:444)
	at kafka.network.Processor.run(SocketServer.scala:340)
	at java.lang.Thread.run(Thread.java:744)
[2015-03-27 14:40:20,292] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor:103)
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
	at kafka.api.PartitionDataSend.writeTo(FetchResponse.scala:70)
	at kafka.network.MultiSend.writeTo(Transmission.scala:101)
	at kafka.api.TopicDataSend.writeTo(FetchResponse.scala:127)
	at kafka.network.MultiSend.writeTo(Transmission.scala:101)
	at kafka.api.FetchResponseSend.writeTo(FetchResponse.scala:231)
	at kafka.network.Processor.write(SocketServer.scala:472)
	at kafka.network.Processor.run(SocketServer.scala:342)
	at java.lang.Thread.run(Thread.java:744)
[2015-03-27 14:40:20,425] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor:103)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at kafka.utils.Utils$.read(Utils.scala:380)
	at kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54)
	at kafka.network.Processor.read(SocketServer.scala:444)
	at kafka.network.Processor.run(SocketServer.scala:340)
	at java.lang.Thread.run(Thread.java:744)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
